<a href="https://colab.research.google.com/github/JoanWaweru/ML-Group-5-Tasks/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from scipy import stats
import matplotlib.pyplot as plt
from numpy import random
import pandas as pd

In [2]:
size=100

In [3]:
fake_data={'Office Size':random.normal(500,50,size), 'Office Price':random.normal(5000,500,size)}

In [4]:
table=pd.DataFrame(fake_data)

In [5]:
table

Office Size  Office Price
0    530.172342   4764.053418
1    548.890228   4613.563890
2    503.925050   4625.608958
3    486.983123   5567.476895
4    421.115098   4312.496411
..          ...           ...
95   488.384252   5482.762605
96   433.578851   5191.328076
97   470.966300   4976.988522
98   520.838767   5412.946830
99   521.249109   5998.455107

[100 rows x 2 columns]

In [6]:
m=10
c=0.5

In [7]:
def y (row):
  yPredict = (fake_data['Office Size'] * m) + c
  return yPredict
#yPredict = (fake_data['Office Size'] * m) + c

In [30]:
#y

In [9]:
table['y'] = table.apply (lambda row: y(row), axis=1)
#table.assign(yPredict=fake_data['yPredict'])

In [10]:
table

Office Size  Office Price  \
0    530.172342   4764.053418   
1    548.890228   4613.563890   
2    503.925050   4625.608958   
3    486.983123   5567.476895   
4    421.115098   4312.496411   
..          ...           ...   
95   488.384252   5482.762605   
96   433.578851   5191.328076   
97   470.966300   4976.988522   
98   520.838767   5412.946830   
99   521.249109   5998.455107   

                                                    y  
0   [5302.2234161814995, 5489.402283252405, 5039.7...  
1   [5302.2234161814995, 5489.402283252405, 5039.7...  
2   [5302.2234161814995, 5489.402283252405, 5039.7...  
3   [5302.2234161814995, 5489.402283252405, 5039.7...  
4   [5302.2234161814995, 5489.402283252405, 5039.7...  
..                                                ...  
95  [5302.2234161814995, 5489.402283252405, 5039.7...  
96  [5302.2234161814995, 5489.402283252405, 5039.7...  
97  [5302.2234161814995, 5489.402283252405, 5039.7...  
98  [5302.2234161814995, 5489.402283252405, 5039.7...  
99  [5302.2234161814995, 5489.402283252405, 5039.7...  

[100 rows x 3 columns]

In [11]:
def z (row):
  return (row['Office Size']-row['y'])**2

In [12]:
table['Mean Squares'] = table.apply (lambda row: z(row), axis=1)

In [13]:
table

Office Size  Office Price  \
0    530.172342   4764.053418   
1    548.890228   4613.563890   
2    503.925050   4625.608958   
3    486.983123   5567.476895   
4    421.115098   4312.496411   
..          ...           ...   
95   488.384252   5482.762605   
96   433.578851   5191.328076   
97   470.966300   4976.988522   
98   520.838767   5412.946830   
99   521.249109   5998.455107   

                                                    y  \
0   [5302.2234161814995, 5489.402283252405, 5039.7...   
1   [5302.2234161814995, 5489.402283252405, 5039.7...   
2   [5302.2234161814995, 5489.402283252405, 5039.7...   
3   [5302.2234161814995, 5489.402283252405, 5039.7...   
4   [5302.2234161814995, 5489.402283252405, 5039.7...   
..                                                ...   
95  [5302.2234161814995, 5489.402283252405, 5039.7...   
96  [5302.2234161814995, 5489.402283252405, 5039.7...   
97  [5302.2234161814995, 5489.402283252405, 5039.7...   
98  [5302.2234161814995, 5489.402283252405, 5039.7...   
99  [5302.2234161814995, 5489.402283252405, 5039.7...   

                                         Mean Squares  
0   [22772471.458241217, 24593961.614001695, 20336...  
1   [22594176.39477574, 24408659.36488064, 2016782...  
2   [23023667.208137523, 24854983.24040777, 205737...  
3   [23186539.080510054, 25024197.454269677, 20727...  
4   [23825218.40956421, 25687534.987774108, 213317...  
..                                                ...  
95  [23173047.496412735, 25010181.346631434, 20714...  
96  [23703699.90392147, 25561350.580033734, 212168...  
97  [23341045.322426498, 25184699.717765823, 20873...  
98  [22861639.159042526, 24686623.410476808, 20420...  
99  [22857715.32828202, 24682545.96527875, 2041685...  

[100 rows x 4 columns]

In [14]:
meanSquareError = (table['Mean Squares'].sum())/size

In [15]:
meanSquareError

array([23068394.55813889, 24901352.12590409, 20616138.03141135,
       19106442.64037829, 13782394.76695869, 20750135.81290778,
       19141776.95986121, 19867042.17482449, 23903703.83647158,
       18422062.68590895, 23273311.68187077, 20325246.60804759,
       24438116.94055001, 20882945.46647419, 15216526.69840799,
       25010624.65072097, 20664813.3946058 , 23049884.81279445,
       22721037.71675641, 18492933.21115097, 17103172.52976267,
       24143949.2223271 , 27070844.38995879, 18471079.54143424,
       16190561.86074397, 18643413.02605905, 26186108.39397711,
       24995385.60436809, 18860830.51844299, 23888035.66827264,
       16493500.36556186, 15429476.95309778, 11935180.15433025,
       15710761.90381951, 28697690.23179669, 22555223.49505531,
       16426684.20988151, 25326556.70058877,  9424257.42662003,
       18111749.30506864, 21368327.32251369, 33831946.82970639,
       23768689.05844139, 22274953.50127497, 21502057.46204014,
       21101271.79589549, 16590315.76037

In [16]:
learningRate=0.01

In [17]:
x=1

In [18]:
newM = (m-(-2/size)*x*table['Mean Squares'].sum())

In [19]:
newM

array([46136799.11627778, 49802714.25180817, 41232286.06282271,
       38212895.28075657, 27564799.53391739, 41500281.62581556,
       38283563.91972242, 39734094.34964898, 47807417.67294317,
       36844135.37181791, 46546633.36374153, 40650503.21609519,
       48876243.88110003, 41765900.93294837, 30433063.39681598,
       50021259.30144195, 41329636.7892116 , 46099779.62558889,
       45442085.43351282, 36985876.42230195, 34206355.05952534,
       48287908.4446542 , 54141698.77991758, 36942169.08286847,
       32381133.72148793, 37286836.05211811, 52372226.78795422,
       49990781.20873619, 37721671.03688598, 47776081.33654529,
       32987010.73112372, 30858963.90619557, 23870370.3086605 ,
       31421533.80763902, 57395390.46359339, 45110456.99011063,
       32853378.41976301, 50653123.40117755, 18848524.85324005,
       36223508.61013728, 42736664.64502738, 67663903.65941277,
       47537388.11688279, 44549917.00254995, 43004124.92408027,
       42202553.59179097, 33180641.52074

In [20]:
newC = (c-(-2/size)*table['Mean Squares'].sum())

In [21]:
newC

array([46136789.61627778, 49802704.75180817, 41232276.56282271,
       38212885.78075657, 27564790.03391739, 41500272.12581556,
       38283554.41972242, 39734084.84964898, 47807408.17294317,
       36844125.87181791, 46546623.86374153, 40650493.71609519,
       48876234.38110003, 41765891.43294837, 30433053.89681598,
       50021249.80144195, 41329627.2892116 , 46099770.12558889,
       45442075.93351282, 36985866.92230195, 34206345.55952534,
       48287898.9446542 , 54141689.27991758, 36942159.58286847,
       32381124.22148793, 37286826.55211811, 52372217.28795422,
       49990771.70873619, 37721661.53688598, 47776071.83654529,
       32987001.23112372, 30858954.40619557, 23870360.8086605 ,
       31421524.30763902, 57395380.96359339, 45110447.49011063,
       32853368.91976301, 50653113.90117755, 18848515.35324005,
       36223499.11013728, 42736655.14502738, 67663894.15941277,
       47537378.61688279, 44549907.50254995, 43004115.42408027,
       42202544.09179097, 33180632.02074

In [28]:
#y = fake_data['Office Size'] * m + c
#plt.scatter(fake_data['Office Size'], fake_data['yPredict'])
#plt.plot(fake_data['Office Size'], fake_data['yPredict'], "Pink")

y = fake_data['Office Size'] * m + c
plt.figure(figsize=(8,6))
plt.scatter(fake_data['Office Size'], fake_data['yPredict'])
plt.plot(fake_data['Office Size'], fake_data['y'])
plt.title('Office Price Prediction')
plt.xlabel('Size')
plt.ylabel('Price')
plt.show()

KeyError: ignored

<Figure size 576x432 with 0 Axes>